### ISSUE TITLE
Bam file error

### ISSUE THREAD

**Issue by averm22** [YangLab/CIRCexplorer#10]
I have run the tophat commands and generated bams using tohat2 fusion search on the unmapped fastq.
However, running them with the CIRCexplorer now gives the error - "Please make sure sample is BAM!"

Does the bam file obtained from tophat2 fusion need to be processed in any other way before passing it to the CIRCexplorer

Thanks

**Comment by kepbod** [comment]
From your error information, your CIRCexplorer parameters contain `-f sample` or `--fusion=sample`, so please check the `sample` file to make sure that it is the correct TopHat-Fusion bam file.

**Comment by averm22** [comment]
Hi 

Thanks for the reply. I looked at the code and figured  I was using an older version of pysam rather than the one with the function used to check the bam file. It ran very well

Thank you 
Akanksha
