### ISSUE TITLE
Unique mapping with TopHat-Fusion

### ISSUE THREAD

**Issue by smm19900210** [YangLab/CIRCexplorer#13]
unique mapping with TopHat-Fusion, tophat2 -o tophat_fusion -p 15 --fusion-search --keep-fasta-order --bowtie1 --no-coverage-search hg19_bowtie1_index tophat/unmapped.fastq, can i  use bowtie2 to mapping with TopHat-Fusion?

**Comment by xingma** [comment]
Yes, you can use bowtie2 as command below:
```
tophat2 -o tophat_fusion -p 15 --fusion-search --keep-fasta-order --no-coverage-search hg19_bowtie2_index tophat/unmapped.fastq
```
However, it may be faster by bowtie1 than bowtie2 as the http://ccb.jhu.edu/software/tophat/fusion_index.shtml said.

**Comment by smm19900210** [comment]
thank a lot! I will try it!

**Comment by smm19900210** [comment]
hi xingma,  i used your programes to identify circRNA, 
Start to convert fustion reads...
Converted 5169 fusion reads!
Start to annotate fusion junctions...
Annotated 0 fusion junctions!
Start to fix fusion junctions...
Fixed 0 fusion junctions!
there are zero circRNA, The ribo− RNA-seq is used.and RNase R treatment is performed. what's the matter with it?

**Comment by kepbod** [comment]
I don't recommend use TopHat-Fusion with bowtie2 as suggested in [TopHat source codes](https://github.com/infphilo/tophat/blob/d451a450b24eab49822910d312a5ce601ce3c4c3/src/tophat.py#L787).
