### ISSUE TITLE
problems in running multiple mapping with tophat

### ISSUE THREAD

**Issue by AliceYu0911** [YangLab/CIRCexplorer#18]
according to the instruction, I do multiple mapping with tophat using the format
tophat2 -a 6 --microexon-search -m 2 -p 10 -G knownGene.gtf -o tophat hg19_bowtie2_index RNA_seq.fastq
the program went wrong, and show error information:
error retrieving prep-reads info

what does that mean? how can I solve it? please help!

**Comment by kepbod** [comment]
This is the problem of tophat but not circexplorer.
