### ISSUE TITLE
issue about not hashable

### ISSUE THREAD

**Issue by cshukai** [YangLab/CIRCexplorer#4]
Hello, 
Thanks for the effor to make the tools avaiable to bioinformatics community. I am currently replicating the analysis mention in your paper to learn this tool .  However, I am having the following error message that I have no clue about how to interpret : 

Start CIRCexplorer 1.0.6
Start to convert fustion reads...
Converted 138505 fusion reads!
Start to annotate fusion junctions...
Traceback (most recent call last):
  File "CIRCexplorer-1.0.6/CIRCexplorer.py", line 459, in <module>
    annotate_fusion(ref_f, temp1, temp2)
  File "CIRCexplorer-1.0.6/CIRCexplorer.py", line 64, in annotate_fusion
    genes, gene_info = parse_ref1(ref_f)  # gene annotations
  File "CIRCexplorer-1.0.6/CIRCexplorer.py", line 203, in parse_ref1
    genes[chrom] = Interval(genes[chrom])
  File "/usr/local/lib/python2.7/dist-packages/interval.py", line 279, in __init__
    raise TypeError("lower_bound is not hashable.")
TypeError: lower_bound is not hashable.
  

The corresponding command is : 
1.tophat2 -a 6 --microexon-search -m 2 -p 10 -G /home/k/Downloads/Homo_sapiens/UCSC/hg19/Annotation/Archives/archive-2013-03-06-11-23-03/Genes/genes.gtf   
/home/k/Downloads/Homo_sapiens/UCSC/hg19/Sequence/Bowtie2Index/genome   
/home/k/Downloads/ncbi/public/sra/SRR901967.fastq

2.bamToFastq -i tophat_out/unmapped.bam -fq tophat_out/unmapped.fastq

3./home/k/Downloads/tophat-2.0.9.Linux_x86_64/tophat2 -o tophat_fusion -p 15 --fusion-search --keep-fasta-order --bowtie1  --no-coverage-search /home/k/Downloads/Homo_sapiens/UCSC/hg19/Sequence/BowtieIndex/genome  tophat_out/unmapped.fastq

4.CIRCexplorer.py -f tophat_fusion/accepted_hits.bam -g /home/k/Downloads/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa  -r  /home/k/Downloads/Homo_sapiens/UCSC/hg19/Annotation/Archives/archive-2013-03-06-11-23-03/Genes/refFlat.txt

**Comment by kepbod** [comment]
I am sorry you used the wrong interval package. The interval package used by CIRCexplorer is https://github.com/kepbod/interval, and your version is from https://pypi.python.org/pypi/interval/1.0.0. They have the same name, but their functions are different. Please do not install it using `pip install interval`. I am sorry for the inconvenience made for you.

**Comment by rborgesm** [comment]
I had the same issue, thank you for replying. Would it be possible to add the correct package link to the Readme file under software so that others can avoid this too?

**Comment by kepbod** [comment]
@rborgesm, we have integrated the interval package into CIRCexplorer by default. You won't need to install the interval package by yourself if you use the latest version of CIRCexplorer.

**Comment by rborgesm** [comment]
I see, I've been using an older version. Thank you.

**Comment by kepbod** [comment]
@rborgesm Done. Thanks for your suggestion.
