### ISSUE TITLE
Paired End Date

### ISSUE THREAD

**Issue by dreamingest** [YangLab/CIRCexplorer#5]
Hi,
Thanks for providing such a great tool!
Just wondering did CIRCexplorer support paired end data? TopHat can align paired-end reads, but when I convert unmapped reads to PE fastq after sorted and indexed the bam file, there were very few reads converted successfully. But if I merged two paired end fastq (R and L) to give a single fastq file, CIRCexplorer worked good.
One more thing, can CIRCexplorer do secondary analysis of Chimeric.out.sam (output fusion detection data from RNA-STAR)? I tried to convert  Chimeric.out.sam to Chimeric.out.bam, and input the bam file to CIRCexplorer, but I got nothing. I compared the output files from TopHat-Fusion and rna-star, they are very similar to each other, and it is kind of strange that CIRCexplorer got nothing from Chimeric.out.bam.
Thanks again for the effor to make the tools avaiable to bioinformatics community.

**Comment by kepbod** [comment]
> Just wondering did CIRCexplorer support paired end data?

I knew some circular RNA prediction methods take advantage of PE sequencing to further confirm the annotation of circular RNAs,  but for CIRCexplorer,  we now treat all the data as single fastq file. we may add more supports for PE data afterwards.


> One more thing, can CIRCexplorer do secondary analysis of Chimeric.out.sam (output fusion detection data from RNA-STAR)?

CIRCexplorer extracts fusion junction reads using special flags (XF) in the bam file offered by TopHat-Fusion. I think RNA-STAR did not offer these flags. So CIRCexplorer now only support TopHat-Fusion. We may support more fusion mappers afterwards.

**Comment by kepbod** [comment]
Add support for PE read. Refer to https://github.com/huboqiang/TanglabCircularRNAPipeline

**Comment by kepbod** [comment]
Refer to [CIRCexplorer2](https://github.com/YangLab/CIRCexplorer2)
