### ISSUE TITLE
KeyError CIRCexplorer.py

### ISSUE THREAD

**Issue by emanuele982** [YangLab/CIRCexplorer#6]
Hi, 
thanks for sharing your useful tool. I'm currently attempting to repeat your example analysis, however I am having the following error message: 
Traceback (most recent call last):
  File "/usr/local/bin/CIRCexplorer.py", line 495, in <module>
    fix_fusion(ref_f, genome_fa, temp2, output, options['--no-fix'])
  File "/usr/local/bin/CIRCexplorer.py", line 128, in fix_fusion
    fusions, fusion_names, fixed_flag = fix_bed(input_f, ref, fa, no_fix)
  File "/usr/local/bin/CIRCexplorer.py", line 324, in fix_bed
    iso_starts, iso_ends = ref['\t'.join([gene, iso, chrom, strand])]
KeyError: 'Usp9x\tNM_009481\tchrX\t+'

Could you please help to fix the problem?
 I really appreciate any help you can provide.

I appreciate any help you can provide

**Comment by kepbod** [comment]
Could you offer your command line?

**Comment by emanuele982** [comment]
Hi thanks for your quick reply, here the command line I used:

tophat2 -a 6 --microexon-search -m 2 -p 8 -G
gencode.vM4.annotation.gtf  -o tophat2 bowtie2_index_mm10
_1.fastq,_2.fastq

tophat2 -o tophat_fusion -p 8 --fusion-search --keep-fasta-order --bowtie1
--fusion-read-mismatches 1 --no-coverage-search bowtie_index_mm10
tophat2/unmapped.fastq

CIRCexplorer.py -f accepted_hits.bam -g genome.fa -r <(sed -e '1d'
refFlat_mm10.txt) --tmp -o CIRC_out

2015-05-18 4:25 GMT+02:00 Xiao-Ou Zhang <notifications@github.com>:

**Comment by kepbod** [comment]
I suspect there are some problems in your refFlat_mm10.txt file, but I am not sure. Could you send your refFlat_mm10.txt to me (kepbod@gmail.com)?
