### ISSUE TITLE
Drop after Start to Annotate  fusion juncions..

### ISSUE THREAD

**Issue by andreirozanski** [YangLab/CIRCexplorer#8]
Hello,
Im doing some tests with data set.
Followed the command lines suggested with tophat.
Fetched ref.txt with fetch_ucsc.py
And got:

Start CIRCexplorer 1.1.1
Start to convert fustion reads...
Converted 102717 fusion reads!
Start to annotate fusion junctions...
Traceback (most recent call last):
  File "CIRCexplorer.py", line 494, in <module>
    annotate_fusion(ref_f, temp1, temp2)
  File "CIRCexplorer.py", line 67, in annotate_fusion
    genes, gene_info = parse_ref1(ref_f)  # gene annotations
  File "CIRCexplorer.py", line 206, in parse_ref1
    genes[chrom] = Interval(genes[chrom])
  File "build/bdist.linux-x86_64/egg/interval.py", line 279, in __init__
TypeError: lower_bound is not hashable.

Is there anything Im doing wrong?

Thanks in advance!

**Comment by kepbod** [comment]
I think you installed the wrong interval package. Please carefully read the README of CIRCexplorer.

**Comment by kepbod** [comment]
Please see issue #4
