### ISSUE TITLE
Lariat search

### ISSUE THREAD

**Issue by akesarwani** [YangLab/CIRCexplorer#9]
Hi, 
I found CIRCexplore a very useful tool for detecting circRNA from RNA-seq. I am interested in detecting circRNA which completely falls in intron (=lariat sequence). I mapped the paired-end reads with tophat and executed this program in the same way as mentioned on github page, but I did not find circRNA associated with lariats, rather from exons. Can you suggest me if some how the tool can enforced to pic circ RNA only from introns.

Thanks.

**Comment by kepbod** [comment]
CIRCexplorer could detect circular intronic long noncoding RNAs (ciRNAs, lariat sequences as you mentioned above ), and these ciRNAs have been labeled in [results](https://github.com/YangLab/CIRCexplorer#output).
